
name: connexa
description: A new Flutter project.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  provider: ^6.0.0
  web_socket_channel: ^2.4.0
  http: ^0.13.6
  file_picker: ^5.2.10
  image_picker: ^0.8.7+5
  mime: ^1.0.4
  emoji_picker_flutter: ^1.6.3
  cryptography: ^2.0.5
  record: ^4.4.4
  image: ^4.1.3
  path_provider: ^2.0.15
  giphy_get: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
